# -*- coding: utf-8 -*-
"""Perceptron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jYfymofjVYNQY6PjJ6Pexu0LsD4ZO2k3
"""

import numpy as np
import pandas as pd

w=np.array([1,-1,0,0.5]).transpose()
xi=[np.array([1,-2,0,-1]).transpose(),np.array([0,1.5,-0.5,-1]).transpose(),np.array([-1,1,0.5,-1]).transpose()]
c=0.1
d=[-1,-1,1]
i=0
print(w)
print(xi)
print(d)

for i in range(len(xi)):
    net=sum(w.transpose()*xi[i])
    print('Aggregation Output:',net)
    o=np.sign(net)
    if o==d[i]:
        print('No Need Of Updation Of Weights')
    else:
        dw=c*(d[i]-o)*xi[i]
        w=w+dw
        print('Weight Vector for This iteration:',w)
    i+=1